const revealItems=document.querySelectorAll('.section-label,.intro-content,.section-head,.project,.service,.about-grid,.availability,.contact-grid');const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}})},{threshold:.08});revealItems.forEach(el=>{el.classList.add('reveal');observer.observe(el)});document.querySelectorAll('.project,.service,.circle-arrow,.big-arrow,.submit').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.06;const y=(e.clientY-r.top-r.height/2)*.06;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});const menu=document.querySelector('.menu-btn');const links=document.querySelector('.nav-links');menu?.addEventListener('click',()=>{links.classList.toggle('open');document.body.classList.toggle('menu-open')});links?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')));

/* Contacto: GitHub Pages es estático, así que FormSubmit entrega los mensajes en el email indicado. */
const contactBox=document.querySelector('.contact-form');
if(contactBox){
contactBox.innerHTML=`<form id="contactForm" action="https://formsubmit.co/ajax/webdeveloperagrp@gmail.com" method="POST" novalidate>
<input type="hidden" name="_subject" value="Nuevo proyecto desde tu portfolio — Gabriela Rodríguez"><input type="hidden" name="_template" value="table"><input type="hidden" name="_captcha" value="true">
<div class="form-row"><label for="contactName">NOMBRE</label><input id="contactName" name="name" type="text" placeholder="Tu nombre" autocomplete="name" required></div>
<div class="form-row"><label for="contactEmail">EMAIL</label><input id="contactEmail" name="email" type="email" placeholder="tu@email.com" autocomplete="email" required></div>
<div class="form-row tall"><label for="contactMessage">PROYECTO</label><textarea id="contactMessage" name="message" placeholder="Cuéntame qué tienes en mente..." required></textarea></div>
<button class="submit" type="submit">Enviar email <span>↗</span></button><p id="formStatus" class="form-status" role="status" aria-live="polite"></p></form>`;
const style=document.createElement('style');style.textContent=`#contactForm .form-row label{font:9px 'DM Mono',monospace;color:var(--muted)}#contactForm input,#contactForm textarea{width:100%;border:0;outline:0;background:transparent;color:var(--text);font:15px Manrope,Arial,sans-serif;padding:0}#contactForm input::placeholder,#contactForm textarea::placeholder{color:#666}#contactForm textarea{min-height:76px;resize:vertical;line-height:1.5}.form-status{min-height:18px;margin:13px 0 0;font:10px 'DM Mono',monospace;color:var(--accent);line-height:1.5}.form-status.error{color:#ff7b7b}.submit{font-family:'DM Mono',monospace;cursor:pointer;background:transparent;color:var(--text)}`;document.head.appendChild(style);
const form=document.querySelector('#contactForm');const status=document.querySelector('#formStatus');
form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;status.className='form-status';status.textContent='Enviando…';const button=form.querySelector('button[type="submit"]');button.disabled=true;button.style.opacity='.55';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!response.ok)throw new Error('send');status.textContent='¡Mensaje enviado! Te responderé lo antes posible.';form.reset()}catch(error){status.className='form-status error';status.textContent='No se pudo enviar. Puedes escribirme directamente por email.'}finally{button.disabled=false;button.style.opacity='1'}});
}