const revealItems=document.querySelectorAll('.section-label,.intro-content,.section-head,.project,.service,.about-grid,.availability,.contact-grid');const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}})},{threshold:.08});revealItems.forEach(el=>{el.classList.add('reveal');observer.observe(el)});document.querySelectorAll('.project,.service,.circle-arrow,.big-arrow,.submit').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.06;const y=(e.clientY-r.top-r.height/2)*.06;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('pointerleave',()=>el.style.transform='')});

/* Menú móvil: navegación desplegable con cierre al tocar un enlace, fuera del menú o Escape. */
const menu=document.querySelector('.menu-btn');const links=document.querySelector('.nav-links');if(menu&&links){menu.setAttribute('type','button');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-controls','mobile-navigation');links.id='mobile-navigation';const closeMenu=()=>{links.classList.remove('open');document.body.classList.remove('menu-open');menu.classList.remove('is-open');menu.setAttribute('aria-expanded','false')};const toggleMenu=()=>{const open=!links.classList.contains('open');links.classList.toggle('open',open);document.body.classList.toggle('menu-open',open);menu.classList.toggle('is-open',open);menu.setAttribute('aria-expanded',String(open))};menu.addEventListener('click',toggleMenu);menu.addEventListener('touchend',e=>{e.preventDefault();toggleMenu()},{passive:false});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});document.addEventListener('click',e=>{if(!links.contains(e.target)&&!menu.contains(e.target))closeMenu()})}

/* Contacto: GitHub Pages es estático. FormSubmit entrega los mensajes al email indicado. */
const contactBox=document.querySelector('.contact-form');
if(contactBox){
contactBox.innerHTML=`<form id="contactForm" action="https://formsubmit.co/webdeveloperagrp@gmail.com" method="POST" novalidate><input type="hidden" name="_subject" value="Nuevo proyecto desde tu portfolio — Gabriela Rodríguez"><input type="hidden" name="_template" value="table"><input type="hidden" name="_captcha" value="true"><input type="hidden" name="_next" value="https://andreinarp2008.github.io/Portfolio/#contact"><div class="form-row"><label for="contactName">NOMBRE</label><input id="contactName" name="name" type="text" placeholder="Tu nombre" autocomplete="name" required></div><div class="form-row"><label for="contactEmail">EMAIL</label><input id="contactEmail" name="email" type="email" placeholder="tu@email.com" autocomplete="email" required></div><div class="form-row tall"><label for="contactMessage">PROYECTO</label><textarea id="contactMessage" name="message" placeholder="Cuéntame qué tienes en mente..." required></textarea></div><button class="submit" type="submit">Enviar email <span>↗</span></button><p id="formStatus" class="form-status" role="status" aria-live="polite"></p></form>`;const style=document.createElement('style');style.textContent=`#contactForm .form-row label{font:9px 'DM Mono',monospace;color:var(--muted)}#contactForm input,#contactForm textarea{width:100%;border:0;outline:0;background:transparent;color:var(--text);font:15px Manrope,Arial,sans-serif;padding:0}#contactForm input::placeholder,#contactForm textarea::placeholder{color:#666}#contactForm textarea{min-height:76px;resize:vertical;line-height:1.5}.form-status{min-height:18px;margin:13px 0 0;font:10px 'DM Mono',monospace;color:var(--accent);line-height:1.5}.form-status.error{color:#ff7b7b}.submit{font-family:'DM Mono',monospace;cursor:pointer;background:transparent;color:var(--text)}.submit:disabled{opacity:.55;cursor:wait}`;document.head.appendChild(style);const form=document.querySelector('#contactForm');const status=document.querySelector('#formStatus');form.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;status.className='form-status';status.textContent='Enviando…';const button=form.querySelector('button[type="submit"]');button.disabled=true;try{const response=await fetch('https://formsubmit.co/ajax/webdeveloperagrp@gmail.com',{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});let data={};try{data=await response.json()}catch{}if(!response.ok||data.success===false)throw new Error('send');status.textContent='¡Mensaje enviado! Te responderé lo antes posible.';form.reset()}catch(error){status.className='form-status error';status.textContent='No se pudo enviar automáticamente. Abriendo el envío seguro…';setTimeout(()=>{HTMLFormElement.prototype.submit.call(form)},700)}finally{button.disabled=false}})}

document.querySelectorAll('img[src$=".webp"]').forEach(img=>{img.src=img.src.replace(/\.webp$/i,'.png')});

/* CALIXTO: asistente local 24/7, sin API key ni envío de conversaciones a terceros. */
const calixto=document.createElement('script');calixto.src='calixto/calixto.js';calixto.defer=true;document.body.appendChild(calixto);